---
- hosts: all
  tasks:
    - name: Deploy Grafana
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana
        ports:
          - "3000:3000"
        restart_policy: always
